version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8555:8080"
    volumes:
      - ".:/app"
    working_dir: /app
    command: bash -c "go build -o main && ./main"
